---
services:
  app:
    container_name: app
    build:
      context: .
    volumes:
      - ./webapp:/app
      - ./certs/:/certs/
      - shared_volume:/data
    # ports:
    #   - "5000:5000"
    expose:
      - "5000"
    environment:
      BF_USER: ${BF_USER}
      BF_PWD: ${BF_PWD}
      BF_API_KEY: ${BF_API_KEY}
    command: sh -c "gunicorn -k gevent -w 1 -b 0.0.0.0:5000 app3:app"
    depends_on:
      - redis
      - streaming_service
    networks:
      - app-network
  
  streaming_service:
    build:
      context: .
    volumes:
      - ./streaming:/app/streaming
      - ./certs/:/certs/
      - shared_volume:/data
    environment:
      BF_USER: ${BF_USER}
      BF_PWD: ${BF_PWD}
      BF_API_KEY: ${BF_API_KEY}
    networks:
      - app-network
    depends_on:
      - redis
    command: python streaming/stream_price.py

  streaming_service_orders:
    build:
      context: .
    volumes:
      - ./streaming:/app/streaming
      - ./certs/:/certs/
      - shared_volume:/data
    environment:
      BF_USER: ${BF_USER}
      BF_PWD: ${BF_PWD}
      BF_API_KEY: ${BF_API_KEY}
    networks:
      - app-network
    depends_on:
      - app
    command: python streaming/stream_orders.py

  redis:
    image: redis:latest
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/etc-letsencrypt:/etc/letsencrypt
    depends_on:
      - app
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/etc-letsencrypt:/etc/letsencrypt
      - ./certbot/var-lib-letsencrypt:/var/lib/letsencrypt
      - ./certbot/var-log-letsencrypt:/var/log/letsencrypt
      - ./certbot/www/:/var/www/certbot/
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew --webroot -w /var/www/certbot; sleep 12h & wait $${!}; done;'"


networks:
  app-network:
    driver: bridge

volumes:
  shared_volume:
