---
services:
  app:
    build:
      context: .
    volumes:
      - ./webapp:/app/webapp
      - ./certs/:/certs/
    ports:
      - "5000:5000"
    environment:
      BF_USER: ${BF_USER}
      BF_PWD: ${BF_PWD}
      BF_API_KEY: ${BF_API_KEY}
    command: python webapp/app2.py
    depends_on:
      - redis
    networks:
      - app-network
  
  streaming_service:
    build:
      context: .
    volumes:
      - ./streaming:/app/streaming
      - ./certs/:/certs/
    environment:
      BF_USER: ${BF_USER}
      BF_PWD: ${BF_PWD}
      BF_API_KEY: ${BF_API_KEY}
    networks:
      - app-network
    depends_on:
      - redis
    command: python streaming/stream_price.py

  redis:
    image: redis:latest
    networks:
      - app-network


networks:
  app-network:
    driver: bridge
