---
services:
  app:
    build:
      context: .
    volumes:
      - ./bf_api:/app/bf_api
      - ./certs/:/certs/
    ports:
      - "5000:5000"
    environment:
      BF_USER: ${BF_USER}
      BF_PWD: ${BF_PWD}
      BF_API_KEY: ${BF_API_KEY}
    command: python bf_api/app.py
