---

services:
  worker:
    build:
      context: .
    volumes:
      - ./app/:/app/
      - ./certs/:/certs/
    environment:
      BF_USER: ${BF_USER}
      BF_PWD: ${BF_PWD}
      BF_API_KEY: ${BF_API_KEY}
    command: tail -f /dev/null
    