---
services:
  app:
    build:
      context: .
    volumes:
      - ./webapp:/app/webapp
      - ./certs/:/certs/
      - shared_volume:/data
    ports:
      - "5000:5000"
    environment:
      BF_USER: ${BF_USER}
      BF_PWD: ${BF_PWD}
      BF_API_KEY: ${BF_API_KEY}
    command: python webapp/app3.py
    depends_on:
      - redis
      - streaming_service
    networks:
      - app-network
  
  streaming_service:
    build:
      context: .
    volumes:
      - ./streaming:/app/streaming
      - ./certs/:/certs/
      - shared_volume:/data
    environment:
      BF_USER: ${BF_USER}
      BF_PWD: ${BF_PWD}
      BF_API_KEY: ${BF_API_KEY}
    networks:
      - app-network
    depends_on:
      - redis
    command: python streaming/stream_price.py

  streaming_service_orders:
    build:
      context: .
    volumes:
      - ./streaming:/app/streaming
      - ./certs/:/certs/
      - shared_volume:/data
    environment:
      BF_USER: ${BF_USER}
      BF_PWD: ${BF_PWD}
      BF_API_KEY: ${BF_API_KEY}
    networks:
      - app-network
    depends_on:
      - redis
    command: python streaming/stream_orders.py

  redis:
    image: redis:latest
    networks:
      - app-network


networks:
  app-network:
    driver: bridge

volumes:
  shared_volume:
